### ISSUE TITLE
Discord invite link on website is expired

### ISSUE THREAD

**Issue by uberspot** [streamingfast/firehose-docs#13]
Hello, 

All discord links I could find in the website or docs have expired. 
Any way to add a persistent one so it's easier to find/use?

**Comment by maoueh** [comment]
@seanmooretechwriter Can you fix that in the docs please.

**Comment by seanmooretechwriter** [comment]
The links have been updated to a never expiring Discord invite link.

https://discord.gg/mYPcRAzeVN
